version: '2'
services:
    bookmart-app:
        image: bookmart
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bookmart-mysql:3306/bookmart?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=bookmart-elasticsearch:9300
        ports:
            - 8080:8080
    bookmart-mysql:
        extends:
            file: mysql.yml
            service: bookmart-mysql
    bookmart-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bookmart-elasticsearch
